FROM webhippie/alpine:latest-arm32v6

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Jq" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT ["/usr/bin/jq"]

RUN apk update && \
  apk upgrade && \
  apk add jq && \
  rm -rf /var/cache/apk/*
